# Generated by Django 5.2.11 on 2026-05-02 10:38

import django.db.models.deletion
import train.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_model', models.CharField(default='yolo11n.pt', max_length=255)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('args_schema_version', models.CharField(default='ultralytics-current', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task', models.CharField(choices=[('detect', 'Detect'), ('segment', 'Segment'), ('classify', 'Classify'), ('pose', 'Pose'), ('obb', 'OBB')], default='detect', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_epoch', models.PositiveIntegerField(default=0)),
                ('total_epochs', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.FloatField(default=0)),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('run_dir', models.CharField(blank=True, max_length=500)),
                ('dataset_yaml_path', models.CharField(blank=True, max_length=500)),
                ('final_args', models.JSONField(blank=True, default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='train.trainingconfig')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='train.trainingpipeline')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDatasetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=train.models.training_image_upload_to)),
                ('label', models.FileField(blank=True, null=True, upload_to=train.models.training_label_upload_to)),
                ('original_image_name', models.CharField(max_length=255)),
                ('original_label_name', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('split', models.CharField(choices=[('train', 'Train'), ('val', 'Validation'), ('test', 'Test'), ('unassigned', 'Unassigned')], db_index=True, default='unassigned', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='train.trainingpipeline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDatasetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField()),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='train.trainingpipeline')),
            ],
            options={
                'ordering': ['pipeline_id', 'index'],
            },
        ),
        migrations.AddField(
            model_name='trainingconfig',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='train.trainingpipeline'),
        ),
        migrations.CreateModel(
            name='TrainingSplitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_percent', models.PositiveSmallIntegerField(default=80)),
                ('val_percent', models.PositiveSmallIntegerField(default=10)),
                ('test_percent', models.PositiveSmallIntegerField(default=10)),
                ('seed', models.PositiveIntegerField(default=42)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_config', to='train.trainingpipeline')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEpochMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField()),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epoch_metrics', to='train.trainingjob')),
            ],
            options={
                'ordering': ['job_id', 'epoch'],
                'constraints': [models.UniqueConstraint(fields=('job', 'epoch'), name='unique_training_job_epoch')],
            },
        ),
        migrations.CreateModel(
            name='TrainingArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('best_model', 'Best model'), ('last_model', 'Last model'), ('results', 'Results'), ('confusion_matrix', 'Confusion matrix'), ('log', 'Log'), ('dataset_zip', 'Dataset ZIP')], max_length=50)),
                ('file', models.FileField(upload_to=train.models.training_artifact_upload_to)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='train.trainingjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'artifact_type'], name='train_train_job_id_e23edf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['status', 'queued_at'], name='train_train_status_f5bf43_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['worker_id', 'locked_at'], name='train_train_worker__8cb541_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdatasetitem',
            index=models.Index(fields=['pipeline', 'split'], name='train_train_pipelin_ec42d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingdatasetclass',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='unique_training_class_name'),
        ),
        migrations.AddConstraint(
            model_name='trainingdatasetclass',
            constraint=models.UniqueConstraint(fields=('pipeline', 'index'), name='unique_training_class_index'),
        ),
        migrations.AddConstraint(
            model_name='trainingconfig',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='unique_training_config_name'),
        ),
    ]
