# Generated by Django 5.2.11 on 2026-02-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotate.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='annotate.project')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.PositiveIntegerField()),
                ('y_min', models.PositiveIntegerField()),
                ('x_max', models.PositiveIntegerField()),
                ('y_max', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotate.image')),
                ('project_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='annotate.projectclass')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectclass',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_class'),
        ),
        migrations.AddConstraint(
            model_name='projectclass',
            constraint=models.UniqueConstraint(fields=('project', 'index'), name='unique_project_class_index'),
        ),
    ]
