# Generated by Django 5.2.11 on 2026-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclass',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
