# Generated by Django 5.2.11 on 2026-02-05 12:16

import annotate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_projectclass_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=annotate.models.project_image_upload_to),
        ),
    ]
