# Generated by Codex on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_alter_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('yolo', 'YOLO')], default='yolo', max_length=20)),
                ('file', models.FileField(upload_to='models/')),
                ('classes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
