# Generated by Django 5.2.11 on 2026-02-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='project_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotate.projectclass'),
        ),
    ]
