# Generated by Django 5.2.11 on 2026-02-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0004_aimodel'),
        ('annotate', '0004_alter_annotation_project_class'),
    ]

    operations = [
    ]
