# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0005_merge_20260206_0506"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="task",
            field=models.CharField(
                choices=[
                    ("detect", "Detect"),
                    ("segment", "Segment"),
                    ("classify", "Classify"),
                    ("pose", "Pose"),
                    ("obb", "OBB"),
                ],
                default="detect",
                max_length=20,
            ),
        ),
    ]
