# Generated by Codex on 2026-02-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0006_aimodel_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoAnnotateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_annotate_configs",
                        to="annotate.aimodel",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_annotate_configs",
                        to="annotate.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoAnnotateClassMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_class", models.CharField(max_length=200)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="annotate.autoannotateconfig",
                    ),
                ),
                (
                    "project_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_annotate_mappings",
                        to="annotate.projectclass",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="autoannotateconfig",
            constraint=models.UniqueConstraint(
                fields=("project", "model"),
                name="unique_auto_annotate_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="autoannotateclassmapping",
            constraint=models.UniqueConstraint(
                fields=("config", "model_class"),
                name="unique_auto_annotate_mapping",
            ),
        ),
    ]
