# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0007_auto_annotate_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoannotateclassmapping",
            name="model_class",
            field=models.PositiveIntegerField(),
        ),
    ]
