# Generated by Django 5.2.11 on 2026-05-04 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_projects_to_active_users(apps, schema_editor):
    project_model = apps.get_model('annotate', 'Project')
    membership_model = apps.get_model('annotate', 'ProjectMembership')
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    user_model = apps.get_model(user_app, user_model)

    active_user_ids = list(
        user_model.objects.filter(is_active=True).values_list('id', flat=True)
    )
    memberships = []
    for project_id in project_model.objects.values_list('id', flat=True):
        memberships.extend(
            membership_model(project_id=project_id, user_id=user_id)
            for user_id in active_user_ids
        )
    membership_model.objects.bulk_create(memberships, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0009_job_image_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_annotation_project_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='annotate.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='annotation_projects', through='annotate.ProjectMembership', through_fields=('project', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member'),
        ),
        migrations.RunPython(
            assign_existing_projects_to_active_users,
            noop_reverse,
        ),
    ]
